// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1NyZwFf4BLk7MBq4DSxA34tFEW4mtE88',
    appId: '1:414434641618:web:7a6c70bec13fba6b014f0b',
    messagingSenderId: '414434641618',
    projectId: 'smart-smash-16e79',
    authDomain: 'smart-smash-16e79.firebaseapp.com',
    storageBucket: 'smart-smash-16e79.firebasestorage.app',
    measurementId: 'G-311ZQ734Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC3F3a7NIBSh4dzvBRgu9ZPY-tksgBu4Y',
    appId: '1:414434641618:android:490728ececdbecb2014f0b',
    messagingSenderId: '414434641618',
    projectId: 'smart-smash-16e79',
    storageBucket: 'smart-smash-16e79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUbYrqp94AE1LLn47qrOC1VdN51cnYDc',
    appId: '1:414434641618:ios:55035a042ad73b15014f0b',
    messagingSenderId: '414434641618',
    projectId: 'smart-smash-16e79',
    storageBucket: 'smart-smash-16e79.firebasestorage.app',
    iosBundleId: 'com.example.smartsmashapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUbYrqp94AE1LLn47qrOC1VdN51cnYDc',
    appId: '1:414434641618:ios:55035a042ad73b15014f0b',
    messagingSenderId: '414434641618',
    projectId: 'smart-smash-16e79',
    storageBucket: 'smart-smash-16e79.firebasestorage.app',
    iosBundleId: 'com.example.smartsmashapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1NyZwFf4BLk7MBq4DSxA34tFEW4mtE88',
    appId: '1:414434641618:web:1fdd597487ccfacc014f0b',
    messagingSenderId: '414434641618',
    projectId: 'smart-smash-16e79',
    authDomain: 'smart-smash-16e79.firebaseapp.com',
    storageBucket: 'smart-smash-16e79.firebasestorage.app',
    measurementId: 'G-4QQY05PN78',
  );
}
